variables:
  DOCKER_DRIVER: overlay2

stages:
  - test

run_tests:
  stage: test
  image: node:10-alpine
  tags:
    - docker
  script:
    - npm install --prefix ./webapp --progress=false
    - npm run test:unit